language: node_js
sudo: false
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_20fd811ec9c2_key -iv $encrypted_20fd811ec9c2_iv
  -in .travis/idsk_frontend_toolkit_npm_push.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.name "GOV.UK Design System CI"
- git config --global user.email "design-system-pipeline@digital.cabinet-office.gov.uk"
- git remote add origin_ssh git@github.com:id-sk/idsk_frontend_toolkit_npm.git
install:
- echo "No dependencies to install"
script:
- "./publish.sh"
deploy:
  provider: npm
  email: govuk-dev@digital.cabinet-office.gov.uk
  api_key:
    secure: gaYyBRr6M6E2ptNDKSKs/R8SMF+WcIOKao6EGpZj6iZY+rjCrfg0Kd5xFo0BsptQ9+8ZFcIfUNY2RpmgrQejrpZ88FsiA3235mY2ugKNg+oyigYq0+dY4cfSXcNvogPz/p53+5M+8oVBHfCCfh2qEt4zRA/4MBfOROgAnjWtCH4=
  on:
    branch: master
